export const COMPETITOR_MAP: Record<string, string[]> = {
  "Scaler": ["upGrad", "Great Learning", "Coding Ninjas", "Masai School", "Newton School", "Simplilearn", "Coursera", "Udemy", "Udacity", "Skillshare"],
  "Qure.ai": ["Aidoc", "PathAI", "Zebra Medical Vision", "Viz.ai", "Tempus", "Enlitic", "Arterys", "DeepMind Health", "Caption Health", "Butterfly Network"],
  "Swiggy": ["Zomato", "Uber Eats", "Blinkit", "Dunzo", "Zepto", "EatSure", "Deliveroo", "DoorDash", "Grubhub", "Just Eat"],
  "mPokket": ["KreditBee", "CASHe", "MoneyTap", "LazyPay", "PaySense", "EarlySalary", "Navi", "Slice", "ZestMoney", "Bajaj Finserv"],
  "AstraZeneca": ["Pfizer", "Novartis", "Roche", "Johnson & Johnson", "Merck", "GSK", "Sanofi", "AbbVie", "Bayer", "Eli Lilly"],
  "Capgemini": ["Accenture", "TCS", "Infosys", "Wipro", "Cognizant", "HCLTech", "IBM", "Deloitte", "Tech Mahindra", "PwC"],
  "Indian Oil": ["BPCL", "HPCL", "Reliance Industries", "Nayara Energy", "Shell", "TotalEnergies", "ONGC", "ExxonMobil", "Chevron", "Gazprom"],
  "Reddit": ["Quora", "X", "Discord", "Facebook Groups", "Tumblr", "4chan", "Stack Overflow", "Medium", "Telegram", "LinkedIn"],
  "Plum": ["Mamaearth", "Minimalist", "Nykaa", "WOW Skin Science", "Sugar Cosmetics", "Dot & Key", "Biotique", "Forest Essentials", "Himalaya", "Lakme"],
  "Observe.ai": ["Gong", "Chorus.ai", "CallMiner", "NICE Nexidia", "Talkdesk", "Five9", "Verint", "Genesys", "Balto", "Tethr"],
  "Demandbase": ["6sense", "ZoomInfo", "HubSpot", "Salesforce", "Marketo", "Pardot", "Clearbit", "Leadfeeder", "Apollo.io", "Terminus"],
  "JumpCloud": ["Okta", "Microsoft Azure AD", "OneLogin", "Ping Identity", "Duo Security", "IBM Security Verify", "Google Workspace IAM", "Auth0", "CyberArk", "SailPoint"],
  "Murf AI": ["ElevenLabs", "Play.ht", "Descript", "Resemble AI", "Lovo.ai", "Speechify", "WellSaid Labs", "Replica Studios", "Coqui AI", "Amazon Polly"],
  "Avaamo": ["Kore.ai", "Yellow.ai", "Cognigy", "Rasa", "IBM Watson Assistant", "Google Dialogflow", "Amazon Lex", "LivePerson", "Drift", "Intercom"],
  "Zeta": ["Razorpay", "Stripe", "PayU", "Cashfree", "Adyen", "Square", "Paytm Payments", "PhonePe", "Visa", "Mastercard"],
  "Jar": ["Groww", "Zerodha", "Upstox", "INDmoney", "ET Money", "Paytm Money", "Kuvera", "Coin by Zerodha", "Smallcase", "Angel One"],
  "Bright Money": ["MoneyTap", "KreditBee", "CASHe", "Navi", "PaySense", "ZestMoney", "Slice", "EarlySalary", "LazyPay", "Bajaj Finserv"],
  "Enkash": ["RazorpayX", "Open", "PayU", "Cashfree", "Stripe", "Paytm Business", "Instamojo", "Airwallex", "Wise", "Brex"],
  "Great Learning": ["upGrad", "Simplilearn", "Coursera", "Udacity", "edX", "Scaler", "Coding Ninjas", "Skillshare", "Udemy", "FutureLearn"],
  "Emeritus": ["upGrad", "Coursera", "edX", "Simplilearn", "Great Learning", "Udacity", "FutureLearn", "Skillshare", "ExecOnline", "2U"],
  "Adda Education": ["Unacademy", "BYJU’S", "Testbook", "Gradeup", "PhysicsWallah", "Vedantu", "Toppr", "Khan Academy", "Embibe", "Career Launcher"],
  "Udhyam Learning": ["Pratham", "Teach For India", "NSDC", "Skill India", "Udacity", "Coursera", "edX", "upGrad", "Simplilearn", "Khan Academy"],
  "College Vidya": ["Shiksha", "CollegeDekho", "Leverage Edu", "upGrad", "Coursera", "edX", "Simplilearn", "Careers360", "Collegedunia", "Unacademy"],
  "UPES": ["Amity University", "LPU", "Manipal University", "Symbiosis", "Sharda University", "Chandigarh University", "SRM", "VIT", "NMIMS", "Ashoka University"],
  "Pearl Academy": ["NIFT", "NID", "JD Institute", "LISAA School", "Vogue Institute", "Amity School of Design", "Arch College", "Istituto Marangoni", "Parsons", "FIT"],
  "National Law School (NLS)": ["NALSAR", "NLUD", "WBNUJS", "GNLU", "NLIU", "HNLU", "RGNUL", "JGLS", "Symbiosis Law School", "Amity Law School"],
  "BCG": ["McKinsey", "Bain & Company", "Deloitte Consulting", "Accenture Strategy", "Kearney", "Oliver Wyman", "EY Consulting", "PwC Advisory", "Roland Berger", "Strategy&"],
  "Sattva Consulting": ["Dalberg", "FSG", "BCG", "Bain", "Deloitte", "EY", "PwC", "KPMG", "Bridgespan Group", "Accenture"],
  "Engie": ["Siemens Energy", "GE Power", "Schneider Electric", "ABB", "TotalEnergies", "Shell", "EDF Energy", "Enel", "Iberdrola", "NextEra Energy"],
  "Suez India": ["Veolia", "Tata Projects", "L&T", "Thermax", "VA Tech Wabag", "Ion Exchange", "Xylem", "Ecolab", "Aquatech", "GE Water"],
  "Goldi Solar": ["Adani Solar", "Tata Power Solar", "Vikram Solar", "Waaree Energies", "RenewSys", "Azure Power", "First Solar", "Canadian Solar", "JinkoSolar", "Trina Solar"],
  "SleepyCat": ["Wakefit", "Sleepyhead", "The Sleep Company", "Sunday Mattress", "Duroflex", "Kurlon", "Nilkamal Sleep", "IKEA Mattresses", "Springtek", "Flo Mattress"],
  "Blue Tokai": ["Third Wave Coffee", "Starbucks", "CCD", "Barista", "Tim Hortons", "Costa Coffee", "Rage Coffee", "Sleepy Owl", "Nescafe", "Bru"],
  "Zappfresh": ["Licious", "FreshToHome", "TenderCuts", "Meatigo", "BigBasket", "Amazon Fresh", "Nature’s Basket", "Spencer’s", "Reliance Fresh", "Grofers"],
  "Swiggy Instamart": ["Blinkit", "Zepto", "Dunzo", "BigBasket", "Amazon Fresh", "Flipkart Quick", "JioMart", "Nature’s Basket", "Spencer’s", "Reliance Fresh"],
  "Hasbro": ["Mattel", "LEGO", "Spin Master", "Funko", "Bandai Namco", "MGA Entertainment", "Playmobil", "Jakks Pacific", "Fisher-Price", "Ravensburger"],
  "Coupang": ["Amazon", "Flipkart", "Alibaba", "JD.com", "Rakuten", "Shopee", "Lazada", "eBay", "Walmart", "Target"],
  "Google": ["Microsoft", "Amazon", "Apple", "Meta", "IBM", "Oracle", "Salesforce", "Adobe", "NVIDIA", "OpenAI"],
  "Netflix": ["Amazon Prime Video", "Disney+ Hotstar", "Hulu", "HBO Max", "Apple TV+", "YouTube", "SonyLIV", "Zee5", "MX Player", "Peacock"],
  "Qualcomm": ["Intel", "NVIDIA", "AMD", "MediaTek", "Broadcom", "Samsung Semiconductor", "Apple Silicon", "IBM", "ARM", "Marvell"],
  "Panasonic": ["Sony", "Samsung", "LG", "Philips", "Whirlpool", "Bosch", "Hitachi", "Toshiba", "Sharp", "Haier"],
  "vivo": ["Xiaomi", "Samsung", "Oppo", "Realme", "OnePlus", "Apple", "Motorola", "Nokia", "Huawei", "Tecno"],
  "HiSense": ["Samsung", "LG", "Sony", "TCL", "Panasonic", "Philips", "Xiaomi", "Haier", "Sharp", "Toshiba"],
  "Simple Energy": ["Ola Electric", "Ather Energy", "TVS Electric", "Bajaj Chetak", "Hero Electric", "Ampere", "Okinawa", "Revolt Motors", "Pure EV", "Ultraviolette"],
  "Montra Electric": ["Tata Motors EV", "Mahindra Electric", "Ashok Leyland EV", "Olectra", "Switch Mobility", "Euler Motors", "Omega Seiki", "Piaggio EV", "Hero Electric", "Ather Energy"],
  "Pixxel": ["Planet Labs", "Maxar", "BlackSky", "Satellogic", "ICEYE", "Spire Global", "Capella Space", "Airbus Defence", "Thales Alenia", "NASA"],
  "KFC": ["McDonald's", "Burger King", "Subway", "Wendy's", "Popeyes", "Chick-fil-A", "Taco Bell", "Domino's", "Pizza Hut", "Dunkin'"],
  "Loreal": ["Estée Lauder", "Unilever", "Procter & Gamble", "Shiseido", "Coty", "Beiersdorf", "Revlon", "Clarins", "AmorePacific", "Mary Kay"],
  "Maybelline New York": ["Revlon", "NYX Professional Makeup", "CoverGirl", "Rimmel London", "MAC Cosmetics", "Clinique", "Urban Decay", "Bobbi Brown", "Neutrogena", "e.l.f. Cosmetics"],
  "Walmart Global Tech": ["Amazon", "Microsoft", "Google", "Meta", "Target", "eBay", "Alibaba", "Salesforce", "Oracle", "SAP"],
  "Fujifilm": ["Canon", "Nikon", "Sony", "Olympus", "Panasonic", "Kodak", "Leica", "Pentax", "Epson", "Ricoh"],
  "IHG": ["Marriott International", "Hilton Worldwide", "Accor", "Hyatt Hotels", "Wyndham Hotels", "Choice Hotels", "Best Western", "Radisson Hotel Group", "Four Seasons", "Airbnb"],
  "slice": ["Uni Cards", "OneCard", "PostPe", "Bullet", "LazyPay", "Jupiter", "Fi Money", "ZestMoney", "mPokket", "Dhani"],
  "Way2News": ["Dailyhunt", "InShorts", "NewsDog", "UC News", "Google News", "Apple News", "Twitter", "Facebook News", "Public App", "Lokmat"],
  "JoshTalks": ["TED", "YouTube", "Cure.fit", "Unacademy", "Skillshare", "Coursera", "Udemy", "LinkedIn Learning", "Khan Academy", "UpGrad"],
  "Namma Yatri": ["Ola", "Uber", "Rapido", "Indriver", "BlablaCar", "Meru", "Zoomcar", "Drivezy", "Bounce", "Shuttl"],
  "Astra Security": ["SiteLock", "Sucuri", "Cloudflare", "Akamai", "Imperva", "Wordfence", "Qualys", "Tenable", "Rapid7", "Check Point"],
  "Battery Smart": ["Sun Mobility", "Yulu", "Bounce", "Ola Electric", "Ather Energy", "Hero Electric", "TVS", "Bajaj", "Bounce Infinity", "Euler Motors"],
  "Nicobar": ["Good Earth", "FabIndia", "Jaypore", "Westside", "Zara", "H&M", "Marks & Spencer", "Anthropologie", "Anokhi", "Anita Dongre"],
  "Caterpillar Inc": ["Komatsu", "John Deere", "Volvo CE", "Hitachi Construction", "Liebherr", "Doosan", "Sany", "Terex", "JCB", "CNH Industrial"],
  "Aurobindo Pharma": ["Teva", "Sandoz", "Mylan", "Sun Pharma", "Cipla", "Dr. Reddy's", "Lupin", "Torrent Pharma", "Glenmark", "Cadila"],
  "Inc.5 Shoes": ["Metro Shoes", "Bata India", "Liberty Shoes", "Khadim's", "Relaxo", "Red Tape", "Paragon", "Mochi", "Skechers", "Adidas"],
  "Asha Ventures": ["Elevar Equity", "Unitus Ventures", "Omnivore", "Chiratae Ventures", "Kalaari Capital", "Blume Ventures", "Lightbox", "Stellaris Venture", "Matrix Partners", "Sequoia India"],
  "KisanKfraft": ["Mahindra Agri", "Escorts", "Sonalika", "TAFE", "John Deere", "VST Tillers", "Force Motors", "Kubota", "Yanmar", "Action Construction Equipment"],
  "Good Bug": ["Culturelle", "Garden of Life", "Align", "Bio-Kult", "Seed Health", "Ritual", "Nordic Naturals", "Olly", "Nature Made", "Solgar"],
  "Zeno Health": ["1mg", "PharmEasy", "Netmeds", "Apollo Pharmacy", "Medlife", "Truemeds", "HealthKart", "Guardian Health", "Wellness Forever", "Frank Ross"],
  "ComputaCenter": ["CDW", "Softcat", "Insight Enterprises", "Bechtle", "SCC", "WWT", "DXC Technology", "NTT Data", "Fujitsu", "Cancom"],
  "Hexagon": ["Trimble", "Bentley Systems", "Autodesk", "PTC", "AVEVA", "Esri", "Topcon", "Siemens Digital", "Dassault Systèmes", "Leica Geosystems"],
  "Decentro": ["RazorpayX", "Open Financial", "Zeta", "Setu", "M2P Fintech", "Cashfree", "Niyo", "BankOpen", "Signzy", "Karza Technologies"],
  "DailyObjects": ["Casetify", "Zivame", "Bewakoof", "Chumbak", "Souled Store", "Wildcraft", "Herschel", "Moleskine", "Bellroy", "Nixon"],
  "Eume": ["Samsonite", "American Tourister", "VIP Industries", "Wildcraft", "Skybags", "Safari Bags", "Mokobara", "Away", "Delsey", "Tumi"],
  "Clinikally": ["Nykaa", "Purplle", "Dermstore", "Cult Beauty", "Sephora", "Ulta Beauty", "SkinStore", "Net-a-Porter", "Lookfantastic", "1mg"],
  "Chupps": ["Crocs", "Skechers", "Bata", "Metro Shoes", "Liberty", "Havaianas", "Birkenstock", "Relaxo", "Puma", "Adidas"],
  "Squadstack": ["Wingman", "Terakeet", "SalesKen", "InsideSales", "Salesloft", "Outreach", "Revenue.io", "LeadSquared", "Amplemarket", "Apollo.io"],
  "Ugaao": ["TrustBasket", "Nurserylive", "Ferns N Petals", "Gardening Pro", "Plants Guru", "Leafy Island", "MyBageecha", "Floweraura", "Greendot", "Perfect Greens"],
  "iLead": ["Amity Online", "Manipal University Online", "LPU Online", "Simplilearn", "upGrad", "Coursera", "Udemy", "LinkedIn Learning", "Great Learning", "Emeritus"],
  "Snabbit": ["TaskRabbit", "Urban Company", "Handy", "Thumbtack", "Angi", "Porch", "HomeAdvisor", "Dunzo", "Zomato", "Swiggy"],
  "PayGlocal": ["Stripe", "Adyen", "PayPal", "Razorpay", "Checkout.com", "Worldpay", "Braintree", "Square", "Payoneer", "Skrill"],
  "GoHighLevel": ["HubSpot", "Salesforce", "ActiveCampaign", "Keap", "ClickFunnels", "Leadpages", "Kartra", "Mailchimp", "Constant Contact", "Zendesk"],
  "Ameliya Ventures": ["Sequoia", "Accel", "Benchmark", "Greylock", "Andreessen Horowitz", "Tiger Global", "SoftBank", "IPV", "Venture Catalysts", "Antler"],
  "Weaver Finance": ["Brex", "Ramp", "Expensify", "Navan", "Airbase", "Spendesk", "Divvy", "Moss", "Pleo", "Soldo"],
  "Chai Bisket": ["TVF", "FilterCopy", "Dice Media", "Girliyapa", "ScoopWhoop", "AIB", "East India Comedy", "Being Indian", "Whack", "Arré"],
  "Mitigata": ["Coalition", "At-Bay", "Corvus Insurance", "Cowbell Cyber", "Resilience", "Zeguro", "CyberCube", "Hiscox", "Beazley", "Chubb"],
  "Scapia": ["Niyo Global", "Fi Money", "Jupiter", "OneCard", "Indie by IndusInd", "BookMyShow (for rewards)", "Zomato", "MakeMyTrip", "ClearTrip", "Airbnb"],
  "Seekho": ["Unacademy", "BYJU'S", "Skillshare", "Coursera", "Udemy", "LinkedIn Learning", "Josh Talks", "CareerLauncher", "Vedantu", "Scaler"],
  "AIP": ["Sequoia", "Accel", "Lightspeed", "SoftBank", "Tiger Global", "Nexus Venture", "Elevation Capital", "Blume Ventures", "Kalaari", "Matrix Partners"],
  "Scale AKA TCF": ["WeWork", "CoWorks", "Awfis", "IndiQube", "Innov8", "91springboard", "The Hive", "Regus", "Smartworks", "Bhive"],
  "Pronto": ["Zomato", "Swiggy", "Uber Eats", "Dunzo", "Zepto", "Blinkit", "BigBasket", "DoorDash", "Grubhub", "Postmates"],
  "Illumine": ["Mindvalley", "Headspace", "Calm", "BetterUp", "CoachHub", "GrowthSpace", "Pluma", "Torch", "Sounding Board", "LeaderAmp"],
  "FRND": ["Tinder", "Bumble", "Hinge", "OkCupid", "Dil Mil", "TrulyMadly", "Aisle", "Coffee Meets Bagel", "Happn", "Badoo"],
  "Smallest": ["Wix", "Squarespace", "Shopify", "Webflow", "Weebly", "Jimdo", "Site123", "GoDaddy", "Duda", "Carrd"],
  "Kissht": ["mPokket", "KreditBee", "CASHe", "MoneyTap", "LazyPay", "PaySense", "Navi", "Slice", "ZestMoney", "Home Credit"],
  "Paasa": ["Razorpay", "Stripe", "Paypal", "Cashfree", "PayU", "Instamojo", "CCAvenue", "BillDesk", "Easebuzz", "Paytm Business"],
  "AxiTrust": ["DocuSign", "Adobe Sign", "HelloSign", "PandaDoc", "SignNow", "Zoho Sign", "RightSignature", "SignEasy", "KeepSolid Sign", "OneSpan"],
  "Urban Degh": ["FabIndia", "Good Earth", "Jaypore", "Nicobar", "Westside", "Zara Home", "IKEA", "H&M Home", "The Label Life", "Chumbak"],
  "GPS Renewables": ["Enerkem", "Fulcrum BioEnergy", "LanzaTech", "Novozymes", "Praxis", "ZeroAvia", "Bloom Energy", "Enphase Energy", "Tesla Energy", "SunPower"],
  "Acquaviva": ["Jaquar", "Kohler", "Hindware", "Cera", "Parryware", "Grohe", "TOTO", "American Standard", "Roca", "Delta"],
  "Alt DRX": ["Strata", "PropertyShare", "hBits", "Konfidis", "YieldStreet", "Fundrise", "RealtyMogul", "Cadre", "Roofstock", "CrowdStreet"],
  "Anand Sweets": ["Haldiram's", "Bikanervala", "Auroville", "Krishna Sweets", "Lal Sweets", "K.C. Das", "Gangotree", "Adyar Ananda Bhavan", "Sangam Sweets", "Sri Krishna Sweets"],
  "AssetPlus": ["Groww", "Zerodha", "Upstox", "ET Money", "Paytm Money", "Scripbox", "Kuvera", "INDmoney", "Goalwise", "Wealthy"],
  "Bayone": ["Infosys", "TCS", "Wipro", "Capgemini", "Accenture", "Cognizant", "HCL", "Mindtree", "LTI", "Zensar"],
  "Bolna.ai": ["OpenAI", "Anthropic", "Google Gemini", "Mistral AI", "Jasper", "Copy.ai", "Writesonic", "Anyword", "Hypotenuse", "Rytr"],
  "BotLab Dynamics": ["Skydio", "DJI", "Parrot", "Autel Robotics", "Kratos", "AeroVironment", "EHang", "Volocopter", "Intel Drones", "Verity"],
  "CHOSEN": ["The Ordinary", "Paula's Choice", "Drunk Elephant", "SkinCeuticals", "La Roche-Posay", "CeraVe", "Vichy", "Kiehl's", "Sunday Riley", "Tatcha"],
  "CSF": ["Bill & Melinda Gates Foundation", "Ford Foundation", "Rockefeller Foundation", "Tata Trusts", "Azim Premji Foundation", "Dasra", "Drishti", "Pratham", "Teach For India", "Room to Read"],
  "Chalet Hotels": ["Taj Hotels", "Oberoi Hotels", "ITC Hotels", "Leela Palaces", "Marriott", "Hyatt", "Hilton", "Accor", "Lemon Tree", "Sarovar"],
  "Edenred": ["Sodexo", "Pluxee", "Paytm Food", "Zeta", "BenefitOne", "Up Group", "Wex", "Fleetcor", "Boon.", "Happay"],
  "Falcon FS": ["Falcon.io", "Sprout Social", "Hootsuite", "Buffer", "Sprinklr", "Khoros", "Salesforce Social Studio", "HubSpot", "Sendible", "Agorapulse"],
  "GradRight (SUNY Buffalo)": ["Leverage Edu", "CollegeDekho", "Shiksha", "IDP Education", "Edwise", "ForeignAdmits", "Admithub", "UniQuest", "Concourse", "BridgeU"],
  "IBDIC": ["IBM", "Cisco", "Dell", "HP", "Huawei", "Nokia", "Juniper", "Arista", "Check Point", "Fortinet"],
  "Omnicom Global Solutions": ["WPP", "Publicis Groupe", "Interpublic Group (IPG)", "Dentsu", "Havas", "Accenture Interactive", "Deloitte Digital", "PwC Digital", "IBM iX", "Cognizant Interactive"],
  "Room to Read": ["Pratham", "Teach For India", "Save the Children", "UNICEF", "World Vision", "Care International", "Oxfam", "Plan International", "Akshaya Patra", "Smile Foundation"],
  "2380 Capital": ["Sequoia", "Accel", "Lightspeed", "SoftBank", "Tiger Global", "Nexus Venture", "Elevation Capital", "Blume Ventures", "Kalaari", "Matrix Partners"],
  "AVPN": ["Giving Tuesday", "Global Impact", "Philanthropy Northwest", "Council on Foundations", "Independent Sector", "CAF America", "United Way", "Rockefeller Philanthropy", "Dalberg", "FSG"],
  "Anu Rathninde": ["Aptiv", "Robert Bosch", "Denso", "Continental AG", "Magna International", "Valeo", "ZF Friedrichshafen", "Faurecia", "Lear Corporation", "Adient"],
  "GNFZ": ["Suez", "Veolia", "Tata Projects", "L&T", "Thermax", "VA Tech Wabag", "Ion Exchange", "Xylem", "Ecolab", "Engie"],
  "GullyLabs": ["The Viral Fever", "FilterCopy", "Dice Media", "ScoopWhoop", "AIB", "East India Comedy", "Being Indian", "Whack", "Arré", "Girliyapa"],
  "IIMA Ventures": ["Sequoia", "Accel", "IPV", "Venture Catalysts", "Antler", "Blume Ventures", "Kalaari", "Nexus", "Elevation", "Matrix"],
  "Ingram Micro": ["TD SYNNEX", "Arrow Electronics", "Avnet", "D&H Distributing", "ScanSource", "Wesco", "Graybar", "Anixter", "Exclusive Networks", "Westcon-Comstor"],
  "JustJobs": ["Naukri.com", "Indeed", "LinkedIn", "Monster India", "TimesJobs", "Glassdoor", "SimplyHired", "Hirist", "Shine.com", "Freshersworld"],
  "Kaizen Analytix": ["Mu Sigma", "Fractal Analytics", "LatentView", "Tiger Analytics", "Absolutdata", "ZS Associates", "Opera Solutions", "Quantzig", "GainInsights", "Tredence"],
  "Mahina": ["FabIndia", "Good Earth", "Jaypore", "Nicobar", "Westside", "Zara Home", "IKEA", "H&M Home", "The Label Life", "Anokhi"],
  "Masin": ["HKA", "FTI Consulting", "Exponent", "Berkeley Research Group", "Navigant", "AlixPartners", "McKinsey", "BCG", "Bain", "Kearney"],
  "Mehta Family Foundation": ["Bill & Melinda Gates Foundation", "Tata Trusts", "Azim Premji Foundation", "Reliance Foundation", "Infosys Foundation", "Ford Foundation", "Rockefeller Foundation", "Wipro Care", "Civic Ventures", "Global Impact"],
  "MetaShop AI": ["Obsess", "Vue.ai", "Syte", "ViSenze", "Donde Search", "Catchoom", "Slyce", "Fashwell", "Clarifai", "Partly"],
  "Milliken": ["Shaw Industries", "Mohawk Industries", "Interface", "Tarkett", "Armstrong World Industries", "Forbo", "Gerflor", "Beaulieu", "Oriental Weavers", "Balta"],
  "Milliken - Flooring": ["Shaw Industries", "Mohawk Industries", "Interface", "Tarkett", "Forbo", "Gerflor", "Beaulieu", "Oriental Weavers", "Balta", "Dixie Group"],
  "Modi Illva": ["Diageo", "Pernod Ricard", "Bacardi", "Beam Suntory", "Brown-Forman", "Radico Khaitan", "Allied Blenders", "United Spirits", "Suntory", "William Grant & Sons"],
  "Musashi": ["Robert Bosch", "Denso", "Magna International", "ZF Friedrichshafen", "Aisin Seiki", "Continental AG", "Valeo", "Faurecia", "Lear Corporation", "Adient"],
  "Novo Camps": ["upGrad", "Coursera", "Udemy", "LinkedIn Learning", "Simplilearn", "Great Learning", "Emeritus", "Scaler", "Byju's", "Unacademy"],
  "Nuuk": ["Yulu", "Bounce", "Ola Electric", "Ather Energy", "Hero Electric", "TVS", "Bajaj", "Bounce Infinity", "Yadea", "Niu"],
  "Optimeus": ["Apple", "Samsung", "Sony", "LG", "Xiaomi", "Oppo", "Vivo", "Realme", "OnePlus", "Google Pixel"],
  "Origin Fresh": ["Licious", "FreshToHome", "Zappfresh", "BigBasket", "Amazon Fresh", "JioMart", "Milkbasket", "Country Delight", "Dunzo", "Blinkit"],
  "Paasa (2)": ["Razorpay", "Stripe", "Paypal", "Cashfree", "PayU", "Instamojo", "CCAvenue", "BillDesk", "Easebuzz", "Paytm"],
  "PetG": ["Heads Up For Tails", "Wiggles", "PetFed", "PetSmart", "Petco", "Chewy", "BarkBox", "PetSuppliesPlus", "Rover", "Wag!"],
  "Playbook Partners": ["Sequoia", "Accel", "Lightspeed", "SoftBank", "Tiger Global", "Nexus Venture", "Elevation Capital", "Blume Ventures", "Kalaari", "Matrix Partners"],
  "Prime Ventures": ["Sequoia", "Accel", "Chiratae", "Kalaari", "Blume", "Nexus", "Elevation", "Matrix", "Lightbox", "Stellaris"],
  "Rakuten Symphony - brand": ["Nokia", "Ericsson", "Samsung", "Huawei", "Cisco", "Juniper", "Mavenir", "Parallel Wireless", "Altiostar", "ZTE"],
  "Rakuten Symphony - Crisis": ["Nokia", "Ericsson", "Samsung", "Huawei", "Cisco", "Juniper", "Mavenir", "Parallel Wireless", "Altiostar", "ZTE"],
  "Rakuten Symphony - Prajaka Profiling": ["Nokia", "Ericsson", "Samsung", "Huawei", "Cisco", "Juniper", "Mavenir", "Parallel Wireless", "Altiostar", "ZTE"],
  "Red Pen": ["Leverage Edu", "CollegeDekho", "Shiksha", "IDP Education", "Edwise", "ForeignAdmits", "Studyportals", "Crimson Education", "The Princeton Review", "Kaplan"],
  "SVP": ["Dalberg", "FSG", "Bain", "BCG", "Deloitte", "EY", "PwC", "KPMG", "Accenture", "Sattva"],
  "Shubhanshu Shukla": ["Indian Space Research Organisation (ISRO)", "SpaceX", "Blue Origin", "Virgin Galactic", "NASA", "ESA", "Roscosmos", "JAXA", "CNSA", "Axiom Space"],
  "South Park Commons": ["Y Combinator", "Techstars", "500 Global", "Antler", "Venture Catalysts", "Entrepreneur First", "Plug and Play", "MassChallenge", "Startupbootcamp", "SOSV"],
  "Straive": ["Appen", "TELUS International", "Lionbridge", "Innodata", "Clarivate", "Wolters Kluwer", "RELX", "Informa", "Pearson", "Cactus Communications"],
  "SunSiyam": ["Soneva", "Four Seasons Maldives", "Anantara", "Lux Resorts", "Jumeirah", "One&Only", "Six Senses", "COMO Hotels", "W Hotels", "St. Regis"],
  "Synergy Capital": ["Sequoia", "Accel", "TPG", "Kohlberg Kravis Roberts (KKR)", "Blackstone", "Carlyle Group", "Warburg Pincus", "Bain Capital", "General Atlantic", "SoftBank"],
  "TWC": ["Third Wave Coffee", "Blue Tokai", "Starbucks", "CCD", "Barista", "Tim Hortons", "Costa Coffee", "Rage Coffee", "Sleepy Owl", "Nescafe"],
  "TrueBlue": ["Kelly Services", "ManpowerGroup", "Adecco", "Randstad", "Robert Half", "Allegis Group", "Indeed", "LinkedIn", "ZipRecruiter", "Upwork"],
  "Udaiti": ["Pratham", "Dasra", "Sattva", "Dalberg", "FSG", "Teach For India", "Room to Read", "Akshaya Patra", "Smile Foundation", "Wipro Foundation"],
  "University of San Diego": ["UCSD", "SDSU", "University of California", "Pepperdine", "Loyola Marymount", "USC", "UCLA", "Stanford", "UC Berkeley", "Santa Clara University"],
  "University of Surrey (UPES IBC)": ["University of Reading", "University of Sussex", "University of Kent", "Loughborough University", "University of Bath", "University of Warwick", "University of Leeds", "UPES", "Amity", "LPU"],
  "University of Western Australia": ["University of Melbourne", "University of Sydney", "UQ", "UNSW", "Monash University", "University of Adelaide", "ANU", "Curtin University", "Murdoch University", "Edith Cowan University"],
  "Upliance.ai": ["Moley", "Samsung", "LG", "Whirlpool", "Bosch", "KitchenAid", "Breville", "Thermomix", "Panasonic", "Haier"],
  "VMS Group": ["CBRE", "JLL", "Knight Frank", "Cushman & Wakefield", "Colliers", "Savills", "Hines", "Brookfield", "Tishman Speyer", "GLP"],
  "YuWaah": ["UNICEF", "Magic Bus", "Dream a Dream", "Lend A Hand India", "Praxis", "Quest Alliance", "TechnoServe", "Akshaya Patra", "Teach For India", "Pratham"],
  "iTel": ["Samsung", "Xiaomi", "Oppo", "Vivo", "Realme", "Infinix", "Techno", "Nokia", "Motorola", "Apple"],
  "v-Titan": ["Medtronic", "Johnson & Johnson", "Stryker", "Becton Dickinson", "Baxter", "Philips Healthcare", "GE HealthCare", "Siemens Healthineers", "Boston Scientific", "Zimmer Biomet"],
  "SenseAI": ["OpenAI", "Anthropic", "Cohere", "Hugging Face", "Stability AI", "Midjourney", "Perplexity", "Grok", "Mistral", "Inflection"],
  "Circuit House": ["Sequoia", "Accel", "Benchmark", "Lightspeed", "Greylock", "Andreessen Horowitz", "Tiger Global", "IPV", "Venture Catalysts", "Antler"],
  "Smile Group": ["Rocket Internet", "SoftBank", "Naspers", "Tiger Global", "Accel", "Sequoia", "Matrix", "Kalaari", "Blume", "Nexus"],
  "Guardian Health": ["Apollo Pharmacy", "Netmeds", "1mg", "PharmEasy", "Medlife", "Truemeds", "HealthKart", "Wellness Forever", "Frank Ross", "MedPlus"],
  "Angara Jewelry": ["Blue Nile", "James Allen", "Brilliant Earth", "Tiffany & Co.", "Cartier", "Signet Jewelers", "Zales", "Kay Jewelers", "Pandora", "Mejuri"],
  "Folk Frequency": ["Spotify", "Apple Music", "YouTube Music", "Amazon Music", "Gaana", "JioSaavn", "SoundCloud", "Pandora", "Deezer", "Tidal"],
  "D2C Insider": ["Shopify", "WooCommerce", "BigCommerce", "Magento", "Wix", "Squarespace", "Amazon", "Flipkart", "Etsy", "Snapdeal"]
};
